name: niv-update

on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  name: niv-update ${{ matrix.source }}
  runs-on: ubuntu-latest
  strategy:
    matrix:
      source: [ nixpkgs ]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - run: nix-env -iA nixos.niv
      - run: niv update ${{source}}
      - run: |
        git config --local user.email 'info@eigenvalue.net'
        git config --local user.name 'Peter Kolloch, Bot'
        git commit -m 'niv update ${{source}}' -a
        git push

