name: niv-update

on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  niv-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source: [ nixpkgs ]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - run: nix-env -iA nixos.niv
      - run: niv update ${{matrix.source}}
      - name: Push Changes
        run: |
          if test -n "$(git status --porcelain)"; then
            git config --local user.email 'info@eigenvalue.net'
            git config --local user.name 'Peter Kolloch, Bot'
            git commit -m 'niv update ${{matrix.source}}' -a
            git push
          else
            echo no changes
          fi